id: P47DFC9FC
initial_creation_type: input
source_metadata:
  title: Katok Situ Chökyi Gyatso Series
  language: en
  description: 'Texts by and about Chökyi Gyatso (chos kyi rgya mtsho), the third
    Katok Situ (kaḥ thog si tu, 1880–1925), nephew and spiritual heir of Jamyang Khyentse
    Wangpo:'
  volume:
    4fe3168dc75b4d9b9ca87ff49834f671:
      title: 'Opening the Door to a Pure Realm: An Aspiration Towards Abhirati'
      parent: Aspiration Prayers
    42452deaefdd414b86cf2bf1c912b7c2:
      title: Prayer of Aspiration Towards Sukhāvatī
      parent: Aspiration Prayers
    59e0b2e4e5a54ea699c23c3f521230f8:
      title: Prayer to the Gurus of the Chöd Lineage
      parent: Lineage Prayers
    b348bcf0ef104b4197fd6020b5ebda41:
      title: The Three Types of Pilgrim
      parent: Pilgrimage
    0b7fc5afd5964412a6a36a7ffc0462de:
      title: A Short Prayer Based on the Life and Liberation of the All-Knowing, All-Seeing
        Jamyang Khyentse Wangpo
      parent: Prayers
    6ad8693dcff94b9f9f50c317c8bae128:
      title: A Song Recalling the Noble Guru’s Kindness
      parent: Songs
    20bdee21a4bc45f79612687d76594c7e:
      title: 'Tremendous Piercing of the Heart: A Lament Recalling the Guru'
      parent: Songs
    5c11099dc43c428e9ed9d7a13a63abe1:
      title: 'The Swift Fulfilment of Wishes: Prayer for the Swift Appearance of the
        Supreme Tulku of the Mañjughoṣa Guru'
      parent: Swift Rebirth Prayers
created_at: '2022-03-01T00:16:12.217121'
last_modified_at: '2022-03-01T00:16:12.217127'
